### ISSUE TITLE
secure headers gem - default config in git?

### ISSUE THREAD

**Issue by jessieay** [fugacious/fugacious#109]
When trying to run the app locally, I get this error:

```
Unexpected error while processing request: Default policy not yet supplied
	/Users/jessieayoung/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/secure_headers-3.6.1/lib/secure_headers/configuration.rb:44:in `get'
	/Users/jessieayoung/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/secure_headers-3.6.1/lib/secure_headers.rb:227:in `config_for'
	/Users/jessieayoung/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/secure_headers-3.6.1/lib/secure_headers/middleware.rb:14:in `call'
```

I assume there is a config somewhere *not* in git for this? Can we add something to go to make it work?

**Comment by jessieay** [comment]
cc @amoose

**Comment by amoose** [comment]
Stale, closing.
